spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: SHAJIANBIN
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8081
